# Site settings
title: Thomas Gaidus's Website
email: tommy.gaidus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  While very much a work in progress, I hope to use this page to share some thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tjg323.github.io" # the base hostname & protocol for your site
twitter_username: tjg323
github_username:  tjg323

# Build settings
markdown: kramdown
