# Site settings
title: Thomas Gaidus
email: tommy.gaidus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Work in progress...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tjg323.github.io" # the base hostname & protocol for your site
twitter_username: tjg323
github_username:  tjg323

# Build settings
markdown: kramdown

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-61848321-1'
